### ISSUE TITLE
Westspur Throughput

### ISSUE THREAD

**Issue by briannne** [mbradds/pipeline-profiles#75]
In the drop down box for Annual Average Throughput, the 2020 and 2021 values for natural gas liquids seem high (especially 2020). I calculated 2020 to be 0.27 and 2021 to be 0.30.

**Comment by mbradds** [comment]
Brianne, this discrepancy is because the annual averages are calculated from the monthly aggregated data instead of the daily data. Averaging by month first changes the weighting of averages for the annual calculation.

I'm not too worried about this because if anyone asks about it, we can provide a valid explanation. Also, the chart tooltip values are consistent with the annual average table.
